# Generated by Django 3.1 on 2020-08-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('tel_no', models.CharField(max_length=30)),
                ('add_1', models.CharField(max_length=100)),
                ('add_2', models.CharField(max_length=100)),
                ('add_3', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=20)),
            ],
        ),
    ]
