# Generated by Django 3.1 on 2020-08-21 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='tel_no',
            new_name='phone',
        ),
    ]
