# Generated by Django 3.1 on 2020-08-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20200821_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='add_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='add_3',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
