# Generated by Django 3.1 on 2020-08-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_auto_20200821_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='fee',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
