# Generated by Django 3.1 on 2020-08-23 11:52

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='comment',
            field=tinymce.models.HTMLField(),
        ),
    ]
