# Generated by Django 3.1 on 2020-09-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20200823_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='edited_by',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
